######################## common config : ########################
server:
  port: 8804
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /oss # 访问前缀

######################## thymeleaf config : ########################
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
######################## oss config : ########################
aliyun:
  oss:
    endpoint: 123 # 阿里云内网或者外网的访问地址
    accessKeyId: 123 # 访问身份验证中用到用户标识
    accessKeySecret: 123 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: 123 # oss的存储空间
    urlPrefix: 123
#    callback: http://localhost:8080/oss/callback # 文件上传成功后的回调地址