######################## common config : ########################
server:
  port: 8803
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /socket # \u8BBF\u95EE\u524D\u7F00

######################## socket-io config : #####################
socket:
  ip: localhost
  port: 9090

