######################## common config : ########################
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /springboot-mybatisplus # 访问前缀

######################## spring config : ########################
spring:
  banner:
    location: classpath:banner.txt # banner 文本文件路径
    # banner 图像文件路径（可以选择 png,jpg,gif 文件）
    #image:
    #  location: classpath:banner.gif
    charset: UTF-8 # banner 文件编码
  main:
    # banner 模式。有三种模式：console/log/off
    # console 打印到控制台（通过 System.out）
    # log - 打印到日志中
    # off - 关闭打印
    banner-mode: console # 是否开启启动图（默认console）
  output:
    ansi:
      enabled: detect # 检查终端是否支持ANSI，是的话就采用彩色输出

  ######################## druid config : ########################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn_and_practice?useUnicode=true&characterEncoding=utf8mb4&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    # druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-active: 20 #最大连接池数量 maxIdle已经不再使用
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于0时poolPreparedStatements会自动修改为true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      #设置访问druid监控页的账号和密码,默认没有（项目地址/druid/index.html）
      stat-view-servlet:
        login-username: admin
        login-password: admin

######################## mybatis-plus config : ########################
mybatis-plus:
  type-aliases-package: cn.code.springbootmybatisplus.entity
  mapper-locations: classpath:mapper/*.xml
  # mybatis 的原生配置
  configuration:
    cache-enabled: false # 是否开启缓存
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则（camel case）映射
    call-setters-on-nulls: true # MyBatis 在使用 resultMap 来映射查询结果中的列，如果查询结果中包含空值的列
    jdbc-type-for-null: 'null' # 如果type为空
  # MyBatis-Plus 全局策略配置
  global-config:
    banner: false # 是否显示mybatis-plus的图标
    db-config:
      id-type: auto # 全局默认主键类型，AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"

######################## log config : ########################
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: error
    cn.code.springbootmybatisplus.mapper: debug