######################## common config : ########################
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /springboot-redis # \u8BBF\u95EE\u524D\u7F00

######################## spring config : ########################
spring:
  banner:
    location: classpath:banner.txt # banner \u6587\u672C\u6587\u4EF6\u8DEF\u5F84
    # banner \u56FE\u50CF\u6587\u4EF6\u8DEF\u5F84\uFF08\u53EF\u4EE5\u9009\u62E9 png,jpg,gif \u6587\u4EF6\uFF09
    #image:
    #  location: classpath:banner.gif
    charset: UTF-8 # banner \u6587\u4EF6\u7F16\u7801
  main:
    # banner \u6A21\u5F0F\u3002\u6709\u4E09\u79CD\u6A21\u5F0F\uFF1Aconsole/log/off
    # console \u6253\u5370\u5230\u63A7\u5236\u53F0\uFF08\u901A\u8FC7 System.out\uFF09
    # log - \u6253\u5370\u5230\u65E5\u5FD7\u4E2D
    # off - \u5173\u95ED\u6253\u5370
    banner-mode: console # \u662F\u5426\u5F00\u542F\u542F\u52A8\u56FE\uFF08\u9ED8\u8BA4console\uFF09
  output:
    ansi:
      enabled: detect # \u68C0\u67E5\u7EC8\u7AEF\u662F\u5426\u652F\u6301ANSI\uFF0C\u662F\u7684\u8BDD\u5C31\u91C7\u7528\u5F69\u8272\u8F93\u51FA

  ######################## druid config : ########################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn_and_practice?useUnicode=true&characterEncoding=utf8mb4&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    #druid\u8FDE\u63A5\u6C60\u914D\u7F6E
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #\u521D\u59CB\u5316\u65F6\u5EFA\u7ACB\u7269\u7406\u8FDE\u63A5\u7684\u4E2A\u6570
      min-idle: 5 #\u6700\u5C0F\u8FDE\u63A5\u6C60\u6570\u91CF
      max-active: 20 #\u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF maxIdle\u5DF2\u7ECF\u4E0D\u518D\u4F7F\u7528
      max-wait: 60000 #\u83B7\u53D6\u8FDE\u63A5\u65F6\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u5355\u4F4D\u6BEB\u79D2
      test-while-idle: true #\u7533\u8BF7\u8FDE\u63A5\u7684\u65F6\u5019\u68C0\u6D4B\uFF0C\u5982\u679C\u7A7A\u95F2\u65F6\u95F4\u5927\u4E8EtimeBetweenEvictionRunsMillis\uFF0C\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u3002
      time-between-eviction-runs-millis: 60000 #\u65E2\u4F5C\u4E3A\u68C0\u6D4B\u7684\u95F4\u9694\u65F6\u95F4\u53C8\u4F5C\u4E3AtestWhileIdel\u6267\u884C\u7684\u4F9D\u636E
      min-evictable-idle-time-millis: 30000 #\u9500\u6BC1\u7EBF\u7A0B\u65F6\u68C0\u6D4B\u5F53\u524D\u8FDE\u63A5\u7684\u6700\u540E\u6D3B\u52A8\u65F6\u95F4\u548C\u5F53\u524D\u65F6\u95F4\u5DEE\u5927\u4E8E\u8BE5\u503C\u65F6\uFF0C\u5173\u95ED\u5F53\u524D\u8FDE\u63A5
      #\u7528\u6765\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684sql \u5FC5\u987B\u662F\u4E00\u4E2A\u67E5\u8BE2\u8BED\u53E5
      #mysql\u4E2D\u4E3A select 'x'
      #oracle\u4E2D\u4E3A select 1 from dual
      validation-query: select 'x'
      test-on-borrow: false #\u7533\u8BF7\u8FDE\u63A5\u65F6\u4F1A\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548,\u5F00\u542F\u4F1A\u964D\u4F4E\u6027\u80FD,\u9ED8\u8BA4\u4E3Atrue
      test-on-return: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u4F1A\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548,\u5F00\u542F\u4F1A\u964D\u4F4E\u6027\u80FD,\u9ED8\u8BA4\u4E3Atrue
      pool-prepared-statements: true #\u662F\u5426\u7F13\u5B58preparedStatement,mysql5.5+\u5EFA\u8BAE\u5F00\u542F
      max-pool-prepared-statement-per-connection-size: 20 #\u5F53\u503C\u5927\u4E8E0\u65F6poolPreparedStatements\u4F1A\u81EA\u52A8\u4FEE\u6539\u4E3Atrue
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #\u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
      use-global-data-source-stat: true #\u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
      #\u8BBE\u7F6E\u8BBF\u95EEdruid\u76D1\u63A7\u9875\u7684\u8D26\u53F7\u548C\u5BC6\u7801,\u9ED8\u8BA4\u6CA1\u6709\uFF08\u9879\u76EE\u5730\u5740/druid/index.html\uFF09
      stat-view-servlet:
        login-username: admin
        login-password: admin

######################## mybatis-plus config : ########################
mybatis-plus:
  type-aliases-package: cn.code.springbootmybatisplus.entity
  mapper-locations: classpath:mapper/*.xml
  # mybatis \u7684\u539F\u751F\u914D\u7F6E
  configuration:
    cache-enabled: false # \u662F\u5426\u5F00\u542F\u7F13\u5B58
    map-underscore-to-camel-case: true # \u662F\u5426\u5F00\u542F\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u89C4\u5219\uFF08camel case\uFF09\u6620\u5C04
    call-setters-on-nulls: true # MyBatis \u5728\u4F7F\u7528 resultMap \u6765\u6620\u5C04\u67E5\u8BE2\u7ED3\u679C\u4E2D\u7684\u5217\uFF0C\u5982\u679C\u67E5\u8BE2\u7ED3\u679C\u4E2D\u5305\u542B\u7A7A\u503C\u7684\u5217
    jdbc-type-for-null: 'null' # \u5982\u679Ctype\u4E3A\u7A7A

######################## log config : ########################
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: error
    cn.code.springbootmybatisplus.mapper: debug